--174
SELECT EMPNO
,RPAD(SUBSTR(EMPNO,1,2),4,'*') AS MASKING_EMPNO
,ENAME
,RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME FROM EMP
WHERE LENGTH(ENAME)>=5
AND LENGTH(ENAME)<6;

SELECT EMPNO, ENAME, SAL
, TRUNC(SAL/21.5/2) AS DAY_PAY
, ROUND(SAL/21.5/8,1) AS TIME_DAY FROM EMP;

/*SELECT EMPNO, ENAME, HIREDATE
,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'¿ù¿äÀÏ'

SELECT EMPNO, ENAME,MGR, DECODE(MGR, */

SELECT DEPTNO, JOB, AVG(SAL)FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >=500 ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);

SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, COUNT(*) FROM EMP
GROUP BY DEPTNO, ROLLUP(JOB);

SELECT DEPTNO, JOB, COUNT(*) FROM EMP
GROUP BY GROUPING SETS(DEPTNO, JOB) ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL),AVG(SAL)
, GROUPING(DEPTNO)
,GROUPING(JOB) FROM EMP
GROUP BY CUBE(DEPTNO, JOB) ORDER BY DEPTNO, JOB;

SELECT DECODE(GROUPING(DEPTNO), 1, 'ALL_DEPT', DEPTNO) AS DEPTNO
, DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB) AS JOB
, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB;

SELECT ENAME FROM EMP WHERE DEPTNO=10;
SELECT DEPTNO, ENAME FROM EMP GROUP BY DEPTNO, ENAME;
SELECT DEPTNO, LISTAGG(ENAME,',')
WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, MAX(SAL) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT * 
FROM(SELECT DEPTNO, JOB, SAL FROM EMP)
PIVOT(MAX(SAL)
FOR DEPTNO IN (10,20,30)) ORDER BY JOB;

SELECT *
FROM(SELECT JOB, DEPTNO, SAL FROM EMP)
PIVOT(MAX(SAL)
FOR JOB IN ('CLERK' AS CLERK
, 'SALESMAN' AS SALESMAN
, 'PRESIDENT' AS PRESIDENT
, 'MANAGER' AS MANAGER
, 'ANALYST' AS ANALYST)
) ORDER BY DEPTNO;

SELECT DEPTNO
,MAX(DECODE(JOB,'CLERK',SAL)) AS "CLERK"
,MAX(DECODE(JOB,'SALESMAN',SAL)) AS "SALESMAN"
,MAX(DECODE(JOB,'PRESIDENT',SAL)) AS "PRESIDENT"
,MAX(DECODE(JOB,'MANAGER',SAL)) AS "MANAGER"
,MAX(DECODE(JOB,'ANALYST',SAL)) AS "ANALYST" FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT *
FROM(SELECT DEPTNO
,MAX(DECODE(JOB,'CLERK',SAL)) AS "CLERK"
,MAX(DECODE(JOB,'SALESMAN',SAL)) AS "SALESMAN"
,MAX(DECODE(JOB,'PRESIDENT',SAL)) AS "PRESIDENT"
,MAX(DECODE(JOB,'MANAGER',SAL)) AS "MANAGER"
,MAX(DECODE(JOB,'ANALYST',SAL)) AS "ANALYST" FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO)
UNPIVOT(
SAL FOR JOB IN ( CLERK, SALESMAN, PRESIDENT, MANAGER, ANALYST))
ORDER BY DEPTNO, JOB, SAL;

SELECT * FROM EMP, DEPT ORDER BY EMPNO;

SELECT *
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO ORDER BY EMPNO;

SELECT *
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

SELECT E.EMPNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

SELECT EMPNO, ENAME, DEPTNO, DNAME, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL >= 3000;

SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL >=2500
AND EMPNO<=9999
ORDER BY E.EMPNO;

SELECT * 
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT *
FROM EMP E, COPY_EMP C
WHERE E.MGR = C.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
, E2.EMPNO AS MGR_MEPNO
, E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
, E2.EMPNO AS MGR_EMPNO
, E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
, E2.EMPNO AS MGR_EMPNO
, E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,E.SAL, E.COMM
,DEPTNO, D.DNAME, D.LOC
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
, DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING(DEPTNO)
WHERE SAL >= 3000
ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
, E. DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
WHERE SAL <= 3000
ORDER BY DEPTNO, E.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
, E2.EMPNO AS MGR_EMPNO
, E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
, E2.EMPNO AS MGR_EMPNO
, E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR
,E2.EMPNO AS MGR_EMPNO
,E2.ENAME AS MGR_ENAME
FROM EMP E1 FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
,DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING(DEPTNO)
WHERE SAL>=3000 AND E.MGR IS NOT NULL
ORDER BY DEPTNO, E.EMPNO;